# Generated by Django 4.2.2 on 2023-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfChecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='Pdf',
        ),
        migrations.AddField(
            model_name='pdf',
            name='file',
            field=models.FileField(default='', upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.CharField(default='titulo', max_length=50),
        ),
    ]
